#!/usr/bin/env python3
"""Generate isolated Paper + Mineflayer worker pairs."""

import argparse
from pathlib import Path


HEADER = """# Generated by scripts/generate_compose.py. Do not edit by hand.
services:
"""


def minecraft_service(rank: int) -> str:
    return f"""  mc{rank}:
    image: itzg/minecraft-server:java21
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: "1.21.4"
      ONLINE_MODE: "FALSE"
      ENABLE_RCON: "TRUE"
      RCON_PASSWORD: minecraft-rl
      DIFFICULTY: easy
      MODE: survival
      VIEW_DISTANCE: "2"
      SIMULATION_DISTANCE: "2"
      SPAWN_PROTECTION: "0"
      MAX_PLAYERS: "8"
      DIFFICULTY: easy
      MEMORY: 700M
      JVM_XX_OPTS: "-XX:+UseG1GC -XX:MaxGCPauseMillis=100"
    ports:
      - "{25565 + rank}:25565"
      - "{25575 + rank}:25575"
    volumes:
      - mc{rank}_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mc-health"]
      interval: 10s
      timeout: 5s
      retries: 30

"""


def bridge_service(rank: int) -> str:
    return f"""  bridge{rank}:
    build: ./bridge
    environment:
      MC_HOST: mc{rank}
      MC_PORT: "25565"
      MC_VERSION: "1.21.4"
      BOT_USERNAME: rl_bot_{rank}
      WS_PORT: "8765"
      RCON_HOST: mc{rank}
      RCON_PORT: "25575"
      RCON_PASSWORD: minecraft-rl
    ports:
      - "{8765 + rank}:8765"
    depends_on:
      mc{rank}:
        condition: service_healthy
    restart: unless-stopped

"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("instances", type=int, nargs="?", default=2)
    parser.add_argument("--output", type=Path, default=Path("docker-compose.yml"))
    args = parser.parse_args()
    if not 1 <= args.instances <= 64:
        parser.error("instances must be between 1 and 64")

    services = "".join(
        minecraft_service(rank) + bridge_service(rank) for rank in range(args.instances)
    )
    volumes = "volumes:\n" + "".join(f"  mc{rank}_data:\n" for rank in range(args.instances))
    args.output.write_text(HEADER + services + volumes, encoding="utf-8")
    print(f"Wrote {args.output} with {args.instances} isolated environments")


if __name__ == "__main__":
    main()
